---
- name: Apache install
  hosts: client
  vars: 
    source: index.html
    destination: /var/www/html

  task: 
    - name: Install Apache
      apt: name=apache2 state=latest

    -name: Print source
      debug:
        var: source
        var: destination
    -name: Print msg
      debug:
        msg: ansible_os_type    
